### ISSUE TITLE
bug: eliminate all console errors

### ISSUE THREAD

**Issue by jibranabsarulislam** [It-s-Saturday/Fornear#32]
errors caused by undefined props and no key stated in .map

**Comment by neeravbhaskarla** [comment]
get I get this issue assigned?

**Comment by jibranabsarulislam** [comment]
of course, thank you @neeravbhaskarla

**Comment by jibranabsarulislam** [comment]
i've updated the readme with updated steps for running the db locally, i hope it helps!


https://github.com/It-s-Saturday/Fornear/blob/a589563a5926665f4493e9d923aebad2809b4abe/README.md?plain=1#L65-L69

**Comment by neeravbhaskarla** [comment]
Hi @jibranabsarulislam, undefined props error is occurring due to rendering element without passing props in the `App.jsx`

<img width="445" alt="Screenshot 2023-06-29 at 7 02 57 PM" src="https://github.com/It-s-Saturday/Fornear/assets/57148990/c82fb8ce-1e2c-4002-ae40-4031eb37f2f2">

Hence, for removing `undefined props error` there are two approaches which are

1. Adding default props by removing `.isRequired` in most of the components
<img width="473" alt="Screenshot 2023-06-29 at 6 24 54 PM" src="https://github.com/It-s-Saturday/Fornear/assets/57148990/18c88c37-cf04-45d9-8acb-d0ed6124204e">

2. Sending default props with the component
<img width="659" alt="Screenshot 2023-06-29 at 7 08 47 PM" src="https://github.com/It-s-Saturday/Fornear/assets/57148990/1036dfda-32a2-4032-b635-7d9f7f87314d">

**Comment by jibranabsarulislam** [comment]
>   Can you suggest a better approach from these two to implement changes in the code?

I think your first approach is good; removing isRequired and setting default props (probably `false` and `null`) makes sense, so we don't clutter component instances with refresh={false} (which would also be an es-lint error)

**Comment by neeravbhaskarla** [comment]
hi @jibranabsarulislam Submitted PR with required changes. Please Check
